- src/components/MessageInput.tsx
- src/components/MessageList.tsx
- src/components/styles/MessageInput.styles.ts
> Ensure many attachments are visible using scroll

- .sauce/config.yml
> FLEXEXP-566 Temporarily remove bugged Saucelab image

- package.json
- src/components/AttachFileButton.tsx
- src/components/AttachFileDropArea.tsx
- src/components/MessageList.tsx
- src/components/MessagingCanvasPhase.tsx
- src/components/__tests__/AttachFileButton.test.tsx
- src/components/__tests__/AttachFileDropArea.test.tsx
- src/components/__tests__/MessagingCanvasPhase.test.tsx
- src/components/styles/AttachFileDropArea.styles.ts
- src/definitions.ts
- src/store/definitions.ts
- src/utils/validateFiles.test.ts
- src/utils/validateFiles.ts
- yarn.lock
> Add drag and drop support for file attachments

- README.md
https://issues.corp.twilio.com/browse/FLEXEXP-738
Not including `package-lock.json` file so code owners will need to run `npm install` to be able to use `npm`.
> FLEXEXP-738 Add note of how to use npm in README

- config-overrides.js
- package.json
- src/components/MessageInput.tsx
- src/components/PreEngagementFormPhase.tsx
- src/utils/useSanitizer.test.tsx
- src/utils/useSanitizer.tsx
- yarn.lock
The Pull Request consists of following changes:
1. Created custom hook to validate and blacklist unwanted characters so that, scripts or eval functions or console logs cannot be added via user inputs, either from the pre-engagement form or from the chat user input.
2. Made use of validator.js library to blacklist and escape unwanted characters.
3. Added HTML based input validation to the "Full Name" form field in the pre-engagement form.
4. Added unit tests for the `useSanitizer` custom hook.
5. Added `@testing-library/react-hooks` to the dev dependencies for writing unit tests of custom hook.
> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided …
> Add validations to the pre-engagement form, and escape unwanted characters from user input

- .eslintrc
- public/index.html
- src/__tests__/index.test.tsx
- src/__tests__/logger.test.ts
- src/__tests__/sessionDataHandler.test.ts
- src/components/FilePreview.tsx
- src/components/MessageInput.tsx
- src/components/Transcript.tsx
- src/components/WebchatWidget.tsx
- src/components/__tests__/ConversationEnded.test.tsx
- src/components/__tests__/FilePreview.test.tsx
- src/components/__tests__/MessageInput.test.tsx
- src/components/__tests__/Transcript.test.tsx
- src/components/__tests__/WebchatWidget.test.tsx
- src/index.tsx
- src/logger.ts
- src/sessionDataHandler.ts
- src/store/actions/__tests__/initActions.test.ts
- src/store/actions/initActions.ts
- src/store/actions/listeners/__tests__/clientListeners.test.ts
- src/store/actions/listeners/clientListener.ts
- src/utils/generateSecurityHeaders.test.ts
- src/utils/generateSecurityHeaders.ts
Added:
1. Basic structure for logger.
2. Unit tests to support the loggerManager.
3. Fixed unit tests.
> basic framework for logger

- .circleci/config.yml
- .gitignore
- jest.config.js
- package.json
- sonar-project.properties
This PR includes:
1. Initial SonarCloud integration as part of Circle CI
> Sonarcloud integration

- .github/dependabot.yml
This Pull Request consists of following changes:
1. Add config yml file for dependabot. This time, I did not add `target-branch` because our default branch is anyways `flex-webchat-ui`; so I don't think it would be necessary for us to include this line.
> Adding dependabot.yml config file

- .env.sample
- cypress.config.ts
- cypress/plugins/helpers/getToken.ts
- cypress/plugins/helpers/getWorker.ts
- cypress/plugins/helpers/interactionHandler.ts
- cypress/plugins/helpers/regionUtil.ts
- cypress/plugins/helpers/twilioClient.ts
- src/utils/regionUtil.ts
Added the required changes to run e2e in different region/env
> FLEXIN-329: Added changes to run e2e in other regions

- package.json
- yarn.lock
This Pull Request consists of:
1. Manual Upgrade -> Express NPM package -> 4.17.2 -> 4.17.3
2. Manual override -> @svgr/webpack 5.5.0 -> 7.0.0
3. Manual upgrade -> recursive-readdir 2.2.2 -> 2.2.3
> npm package manual upgrade

- public/demo.html
- public/index.html
Adding support for demo app to start
> FLEXIN-272 - Booting react app for demo app

- public/app.css
- public/app.js
- public/demo.html
Moved css and javascript part to more granular files
> [FLEXIN-272] - Minimising html for aws load-balancer

- .circleci/config.yml
- package.json
- src/utils/validateFiles.test.ts
- yarn.lock
updated the project to run with Node18 and also update the node version in circleci and sonarcloud
> FLEXIN-360: Updated Node 14 to Node 18

- .circleci/config.yml
> FLEXIN-478: skipping e2e

- public/app.js
- src/__tests__/index.test.tsx
- src/index.tsx
- src/store/definitions.ts
> FLEXIN-486 - Adding functionality to toggle the widget opening

- public/app.js
> [FLEXIN-477] - setting default theme to light theme

- src/components/MessageList.tsx
- src/components/MessagingCanvasPhase.tsx
- src/components/__tests__/MessagingCanvasPhase.test.tsx
> [Flexin 535] - UI now sends User's Query as conversation

- src/__tests__/index.test.tsx
- src/__tests__/sessionDataHandler.test.ts
- src/components/MessageList.tsx
- src/components/MessagingCanvasPhase.tsx
- src/components/PreEngagementFormPhase.tsx
- src/components/WebchatWidget.tsx
- src/components/__tests__/MessagingCanvasPhase.test.tsx
- src/components/__tests__/PreEngagementFormPhase.test.tsx
- src/components/__tests__/WebchatWidget.test.tsx
- src/definitions.ts
- src/index.tsx
- src/sessionDataHandler.ts
- src/store/definitions.ts
Clean up test cases
Added a single point of processing token response
Updated contactBackend signature
> [FLEXIN-535] - UI Cleanup Part III

- public/app.css
This pr updates png images to distortless svg.
> Updating to latest svg icon

- package.json
- yarn.lock
> Removing sendgrid from dependency list

- src/utils/generateSecurityHeaders.test.ts
- src/utils/generateSecurityHeaders.ts
> [FLEXIN-638] - Reusing existing UserAgent header

- LICENSE
- src/index.tsx
1. Updated Copyright year in the LICENSE file.
2. Added the copyright notice to the root index (webchat main entry) file.
> Updating License Copyright year. Adding it to root index

- .circleci/config.yml
- cypress.config.ts
- cypress/e2e/General/WebchatGeneral.cy.ts
- cypress/plugins/helpers/getWorker.ts
- package.json
- scripts/e2eCleanupExistingTasks.js
> FLEXIN-494: bringing back e2e

- CONTRIBUTING.md
First Draft of CONTRIBUTING.md
> CONTRIBUTING.md file first draft

- README.md
> [FLEXIN-590] - pointing to correct links and documentation fix

- server/controllers/initWebchatController.js
- Added Mixpanel header to the `/initWebchat` endpoint
> Mixpanel header for RA

- README.md
This pull request includes a significant update to the `README.md` file, mainly to inform users about the deprecation of the repository and to guide them to the new location for ongoing development.
Changes to `README.md`:
* Added a **Deprecation Notice** section to inform users that the repository will no longer be maintained and that future development has moved to an internal Twilio repository.
* Provided a link to the Twilio Documentation for those who want to use or see the latest updates for Webchat UI V3.
> FLEXEXP-2740: adding deprecation notice

- README.md
> FLEXEXP-2740 typo fix

- README.md
> FLEXEXP-2740 revert deprecation notice

- README.md
> FLEXEXP-2740 january update
